###
# @name login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "steve@example.com",
    "password": "123456"
}
###
@authToken = {{login.response.body.token}}
GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
@authToken = {{login.response.body.token}}
PUT http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Steve Smith",
    "email": "steve@gmail.com",
    "password": 123456
}
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Steve Smith",
    "email": "steve@example.com",
    "password": "123456"
}